import type { WorkflowState, WorkflowStatus } from './workflow';

const API_BASE_URL = 'http://127.0.0.1:8000';

// Shape returned by the new FastAPI backend (backend/app/)
type BackendTask = {
  id: string;                          // UUID string
  original_prompt: string;
  structured_prompt: string | null;
  bug_list_constraints: string[];
  current_phase: string;
  search_provider: string;
  difficulty_score: number | null;
  selected_model: string | null;
  generated_code: string | null;
  sandbox_iterations: number;
  max_iterations: number;
  created_at: string;
  updated_at: string;
};

// Map new backend phase strings → frontend status tokens
const phaseMap: Record<string, WorkflowStatus> = {
  '1_INTENT_PARSING':   'context',
  '2_PRECHECK_GREPTILE': 'risk',
  '3_HUMAN_IN_THE_LOOP': 'pendingApproval',
  '4_COMPUTE_ROUTING':   'execution',
  '5_SANDBOX_TESTING':   'sandbox',
  FINISHED:              'finished',
  FAILED:                'failed',
};

const normalizeTask = (task: BackendTask): WorkflowState => ({
  taskId: task.id,          // UUID string
  status: phaseMap[task.current_phase] ?? 'failed',
  userRequest: task.original_prompt,
  prompt: task.structured_prompt ?? '',
  confidence: task.difficulty_score ? task.difficulty_score * 20 : 0,
  references: [],           // new backend doesn't return references directly
  risks: (task.bug_list_constraints ?? []).map((c) => ({
    title: c,
    severity: 'medium' as const,
    mitigation: c,
  })),
  route: task.selected_model
    ? {
        difficulty: task.difficulty_score ?? 0,
        model: task.selected_model,
        provider: 'Clod.io',
        budget: '',
        latency: '',
        rationale: '',
      }
    : undefined,
  code: task.generated_code
    ? {
        title: 'generated_output.py',
        language: 'py',
        summary: `Generated by ${task.selected_model ?? 'AI'}`,
        patch: task.generated_code,
      }
    : undefined,
  repairAttempts: task.sandbox_iterations ?? 0,
  maxRepairAttempts: task.max_iterations ?? 3,
  review: {
    status: 'pending',
    summary: 'No sandbox review has run yet.',
    tests: [],
  },
  events: [],
});

const postJson = async <T>(path: string, body: unknown): Promise<T> => {
  const response = await fetch(`${API_BASE_URL}${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  const payload = await response.json();
  if (!response.ok) {
    throw new Error(payload.detail || payload.error || `Request failed with HTTP ${response.status}`);
  }
  return payload;
};

export const createTask = async (request: string) => {
  const task = await postJson<BackendTask>('/api/v1/tasks/', { request });
  return normalizeTask(task);
};

// Approve: send { approved: true, edited_prompt } to the approve endpoint
export const approveTask = async (taskId: string, prompt: string) => {
  const task = await postJson<BackendTask>(`/api/v1/tasks/${taskId}/approve`, {
    approved: true,
    edited_prompt: prompt || null,
  });
  return normalizeTask(task);
};

// Reject: send { approved: false } to the approve endpoint (no separate /reject route)
export const rejectTask = async (taskId: string) => {
  const task = await postJson<BackendTask>(`/api/v1/tasks/${taskId}/approve`, {
    approved: false,
  });
  return normalizeTask(task);
};
