import type { WorkflowState, WorkflowStatus } from './workflow';

const API_BASE_URL = 'http://127.0.0.1:8000';

// Shape returned by the new FastAPI backend (backend/app/)
type BackendTask = {
  id: string;
  original_prompt: string;
  structured_prompt: string | null;
  bug_list_constraints: string[];
  current_phase: string;
  search_provider: string;
  difficulty_score: number | null;
  selected_model: string | null;
  generated_code: string | null;
  sandbox_iterations: number;
  max_iterations: number;
  error_message?: string | null;
  created_at: string;
  updated_at: string;
};

// Map backend phase strings → frontend WorkflowStatus tokens
const phaseMap: Record<string, WorkflowStatus> = {
  '1_INTENT_PARSING':    'context',
  '2_PRECHECK_GREPTILE': 'risk',
  '3_HUMAN_IN_THE_LOOP': 'pendingApproval',
  '4_COMPUTE_ROUTING':   'execution',
  '5_SANDBOX_TESTING':   'sandbox',
  FINISHED:              'finished',
  FAILED:                'failed',
};

export const normalizeTask = (task: BackendTask): WorkflowState => ({
  taskId: task.id,
  status: phaseMap[task.current_phase] ?? 'context',
  errorMessage: task.error_message || undefined,
  userRequest: task.original_prompt,
  prompt: task.structured_prompt ?? '',
  confidence: task.difficulty_score ? Math.min(100, task.difficulty_score * 20) : 0,
  references: [],
  risks: (task.bug_list_constraints ?? []).map((c) => ({
    title: c,
    severity: 'medium' as const,
    mitigation: c,
  })),
  route: task.selected_model
    ? {
        difficulty: task.difficulty_score ?? 0,
        model: task.selected_model,
        provider: 'Clod.io',
        budget: '',
        latency: '',
        rationale: `Generated by ${task.selected_model}`,
      }
    : undefined,
  code: task.generated_code
    ? {
        title: 'generated_output.py',
        language: 'py',
        summary: `Generated by ${task.selected_model ?? 'AI'}`,
        patch: task.generated_code,
      }
    : undefined,
  repairAttempts: task.sandbox_iterations ?? 0,
  maxRepairAttempts: task.max_iterations ?? 3,
  review: {
    status: 'pending',
    summary: 'No sandbox review has run yet.',
    tests: [],
  },
  events: [],
});

const extractErrorMessage = (payload: unknown): string => {
  if (!payload || typeof payload !== 'object') return String(payload ?? 'Unknown error');
  const p = payload as Record<string, unknown>;
  const detail = p['detail'] ?? p['error'];
  if (!detail) return 'Unknown error';
  if (typeof detail === 'string') return detail;
  if (Array.isArray(detail)) {
    return detail
      .map((d) => (typeof d === 'object' && d !== null ? (d as Record<string, unknown>)['msg'] ?? JSON.stringify(d) : String(d)))
      .join('; ');
  }
  return JSON.stringify(detail);
};

const postJson = async <T>(path: string, body: unknown): Promise<T> => {
  const response = await fetch(`${API_BASE_URL}${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  const payload = await response.json();
  if (!response.ok) {
    throw new Error(extractErrorMessage(payload));
  }
  return payload;
};

const getJson = async <T>(path: string): Promise<T> => {
  const response = await fetch(`${API_BASE_URL}${path}`);
  const payload = await response.json();
  if (!response.ok) {
    throw new Error(payload.detail || payload.error || `HTTP ${response.status}`);
  }
  return payload;
};

/**
 * Create a task (returns immediately in PHASE_1 while AI runs in background).
 * Then poll until the phase advances to PHASE_3_HITL (pendingApproval) or FAILED.
 */
export const createTask = async (
  request: string,
  onProgress: (state: WorkflowState) => void,
): Promise<WorkflowState> => {
  // POST — returns instantly with PHASE_1 task
  const task = await postJson<BackendTask>('/api/v1/tasks/', { request });
  let state = normalizeTask(task);
  onProgress(state);

  // Poll until we hit pendingApproval, finished, or failed
  const terminalPhases = new Set(['pendingApproval', 'finished', 'failed']);
  for (let i = 0; i < 120; i++) {
    await new Promise((r) => setTimeout(r, 3000)); // poll every 3s
    try {
      const updated = await getJson<BackendTask>(`/api/v1/tasks/${task.id}`);
      state = normalizeTask(updated);
      onProgress(state);
      if (terminalPhases.has(state.status)) return state;
    } catch {
      // Transient poll error — keep trying
    }
  }
  
  // If we exit the loop without returning, it timed out
  state.status = 'failed';
  state.errorMessage = 'Frontend timeout: Task is taking too long. Check backend logs for rate limits or hangs.';
  onProgress(state);
  return state;
};

// Approve: send { approved: true, edited_prompt } to the approve endpoint
export const approveTask = async (
  taskId: string, 
  prompt: string,
  onProgress: (state: WorkflowState) => void
): Promise<WorkflowState> => {
  const task = await postJson<BackendTask>(`/api/v1/tasks/${taskId}/approve`, {
    approved: true,
    edited_prompt: prompt || null,
  });
  let state = normalizeTask(task);
  onProgress(state);

  // Poll for phase 4 and 5
  const terminalPhases = new Set(['finished', 'failed']);
  for (let i = 0; i < 120; i++) {
    await new Promise((r) => setTimeout(r, 3000));
    try {
      const updated = await getJson<BackendTask>(`/api/v1/tasks/${taskId}`);
      state = normalizeTask(updated);
      onProgress(state);
      if (terminalPhases.has(state.status)) return state;
    } catch {
      // transient poll error
    }
  }

  state.status = 'failed';
  state.errorMessage = 'Frontend timeout: Sandbox is taking too long.';
  onProgress(state);
  return state;
};

// Reject: dedicated /reject route
export const rejectTask = async (taskId: string): Promise<WorkflowState> => {
  const task = await postJson<BackendTask>(`/api/v1/tasks/${taskId}/reject`, {});
  return normalizeTask(task);
};
